-- **Q1:** What is the total revenue generated by male vs. female customers?

Select gender, sum(purchase_amount) as total_purchase_amount from customer
group by gender


-- **Q2:** Which customers used a discount but still spent more than the average purchase amount?

Select customer_id, purchase_amount from customer
where purchase_amount >= (select avg(purchase_amount) from customer)
And discount_applied = 'Yes'

-- **Q3:** Which are the top 5 products with the highest average review rating?

Select item_purchased, round(avg(review_rating):: numeric,2) as ratings from customer
group by item_purchased
order by ratings desc
limit 5

-- **Q4:** Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type, round(avg(purchase_amount),2) from customer
where shipping_type  in ('Express', 'Standard' )
group by shipping_type


-- **Q5:** Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status, Count(customer_id) as total_customer, round(avg(purchase_amount), 2) as avg_spend, sum(purchase_amount) as total_purchased_amount from customer
group by subscription_status


-- **Q6:** Which 5 products have the highest percentage of purchases with discounts applied?

SELECT 
    item_purchased,
    COUNT(*) AS total_purchases,
    SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discounted_purchases,
    ROUND(
        (SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0) / COUNT(*), 
        2
    ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q7 :- What is the share of each category in purchase amount
select category, round(sum(purchase_amount)*100/(select sum(purchase_amount) from customer),2) as perctan_category from customer
group by category
order by perctan_category desc

-- Q8 :- Segment customers into New, Returing, and Loyal based on their total number of previous purchases, and show the count

with customer_type as(
	Select customer_id,  previous_purchases, 
	case when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returing'
	else 'Loyal' 
	End as customer_segment
	from customer
)

select customer_segment, Count(*) from customer_type
group by customer_segment

-- Q9 :- What are the top 3 products purchased from each category ?

WITH item_counts as (select category, item_purchased,  count(customer_id) as total_orders, 
row_number() over(partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category, item_purchased)

Select * from item_counts
where item_rank  <=3

-- Q10 :- Are customer who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

With subs_status as (Select subscription_status, previous_purchases from customer
Where previous_purchases > 5)

Select subscription_status, count(subscription_status) from subs_status
group by subscription_status


-- Q10 what is the revenue contribution for each age group ?

Select age_group, sum(purchase_amount) as total_purchases,
round(sum(purchase_amount)*100/(select sum(purchase_amount) from customer),2) as share_in_purchase
from customer
group by age_group
order by share_in_purchase desc


